name: Act8
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_animations: ^5.0.0
  page_transition: ^2.0.9
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/Background.png
    - assets/images/JugueteBebe1.png
    - assets/images/JugueteFamiliar2.png
    - assets/images/JugueteNinas6.png
    - assets/images/JugueteNino2.png
    - assets/images/Icon_Profile.png


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
